### ISSUE TITLE
Swagger UI multitenancy

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-swagger#21]
Would be nice to map the same swagger-ui servlet to multiple URL paths serving different specs depending on the path. For this let's change configuration to allow multiple sets of specs:

```yaml
swaggerui:
  spec1:
     specUrl: "https://example.org/spec1.yml"
     uiPath: "/doc/spec1"
  spec2:
     specPath: "spec2.yml"
     uiPath: "/doc/spec2"
```

## Upgrade Notes

Configuration format is not backwards compatible. You will need to change configurations from this:

```yaml
swaggerui:
  specUrl: "https://example.org/spec1.yml"
``` 
to something like this:
```yaml
swaggerui:
  default:
     specUrl: "https://example.org/spec1.yml"
```
