### ISSUE TITLE
"bootique-swagger" - allow to map spec URL via config

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-swagger#23]
Once we implement https://github.com/bootique/bootique-jersey/issues/51, we should be able to allow dynamic mapping of `/openapi.yml|json` driven by configuration. 

Another thing to consider here is multi-tenancy (i.e. the ability to map multiple models in a single app)

As documented in README, the new config looks like this:

```yaml
swagger:
  specs:
     # arbitrary name of a spec endpoint... Multiple specs at different URLs are supported
     default:

       # desired URL paths of JSON and YAML resources. Resolved relative to Jersey root URL
       pathJson: "model/openapi.json"
       pathYaml: "model/openapi.yaml"

       # where the spec sources are
       spec: "classpath:main-openapi.yml"
       overrideSpec: "classpath:extra-openapi.yml"
       resourcePackages:
         - "com.example.api"
       resourceClasses:
         - "com.example.Api"
```
