### ISSUE TITLE
Overrides remove existing components from OpenAPI

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-swagger#29]
If I have the following config file and OpenAPI overrides descriptor, all components detected from annotations are removed from the final doc object, and only the "securitySchemes" component remains. 

Expected: components from annotations and overrides must be merged together.

```yaml
-- app config.yml
swagger:
  specs:
    default:
      overrideSpec: "classpath:overrides.yml"

-- overrides.yml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```
