### ISSUE TITLE
Flag to explicitly disable OpenAPI endpoints

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-swagger#39]
Let's add a config flag to explicitly disable OpenAPI endpoints in the webapp. This would allow to "scrape" the OpenAPI descriptor via the `--generate-spec` command, while hiding it in the running app:

```yaml
swagger:
  specs:
    default:
      noWebAccess: true
```
