### ISSUE TITLE
 Flag to explicitly disable Swagger console

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-swagger#40]
Just like in #39, let's create a similarly-named flag for swagger-ui console that would disable it on demand. One of the first "feature toggles" in Bootique...

```yaml
swaggerui:
   default:
      noWebAccess: true
```
